### ISSUE TITLE
sclang.start after sclang.stop fails

### ISSUE THREAD

**Issue by goonzoid** [davidgranstrom/scnvim-tmux#3]
The first time I start and stop SC (by calling `sclang.start` & `sclang.stop` or `:SCNvimStart` & `:SCNvimStop`), it works great! However, the next time I try to start it again (without quitting and reopening NeoVim), I get the following error:
```
Error executing vim.schedule lua callback: ...plugged/scnvim-tmux/lua/scnvim/_extensions/tmux/init.lua:97: attempt to use a closed file
stack traceback:
        [C]: in function 'write'
        ...plugged/scnvim-tmux/lua/scnvim/_extensions/tmux/init.lua:97: in function 'default_fn'
        /Users/wminor/.vim/plugged/scnvim/lua/scnvim/action.lua:45: in function 'on_output'
        /Users/wminor/.vim/plugged/scnvim/lua/scnvim/sclang.lua:33: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```
Here is a stripped down version of my scnvim config that is sufficient to reproduce the issue:
```lua
local scnvim = require 'scnvim'

scnvim.setup({
  extensions = {
    tmux = {
      cmd = 'tail',
      args = { '-F', '$1' }
    },
  },
})

scnvim.load_extension 'tmux'
```

Versions:
- NeoVim: 0.9.0
- scnvim: `c44d57a`
- scnvim-tmux: `9c9e55d`
- tmux: 3.3a
- zsh: 5.9
- macOS: 13.4

Please let me know if I can provide any additional info or if there's anything you'd like me to do to help debug. Thanks for the awesome plugins!

**Comment by rumblesan** [comment]
Had a quick dig into this as I've been hitting the same issue.

Problem seems to be that on calling `sclang.stop` the extension runs `tmux.destroy` which closes the `tmux.post_buffer` file handle but keeps it in the extensions main `tmux` table.

When `tmux.open` gets called on the second `sclang.start` call the `post_buffer` doesn't get reopened because it already exists.
https://github.com/davidgranstrom/scnvim-tmux/blob/main/lua/scnvim/_extensions/tmux/init.lua#L51

Having `tmux.destroy` explicitly set `tmux.post_buffer` to nil seems to sort it, but I need to have more of a look to get a better handle on the way extensions work
